spring.application.name=proxy
server.port=8000
spring.main.web-application-type=reactive
movies.service.url=${MOVIES_SERVICE_URL:http://default.url}
monolith.url=${MONOLITH_URL:http://default.url}
gradual.migration=${GRADUAL_MIGRATION:false}
movie.migration.percent=${MOVIES_MIGRATION_PERCENT:50}